apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: cluster-gcs
  namespace: postgres-operator
  annotations:
    postgres-operator.crunchydata.com/pgbackrest-restore: id1
spec:
  backups:
    pgbackrest:
      configuration:
      - secret:
          # already created in local cluster
          name: pgo-gcs-creds
      global:
        repo1-path: /pgbackrest/postgres-operator/cluster-gcs/repo1
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-4
      # For one-shot full backups
      # Backup is triggered by an annotation i.e.
      # postgres-operator.crunchydata.com/pgbackrest-backup="$(date)"
      manual:
        options:
        - --type=full
        repoName: repo1
      # The scheduled backup
      repos:
      - gcs:
          bucket: postgresql-operators-backup-test
        name: repo1
        schedules:
          differential: 0/5 * * * *
          full: 0 1 * * *
      # For in-place restores
      # Restore is triggered by an annotation i.e.
      # postgres-operator.crunchydata.com/pgbackrest-restore=id1
      restore:
        # Must be set to "true" to restore
        enabled: true
        options:
        - --type=time
        # This is for PITR recovery
        - --target="2023-03-17 09:50:00+01"
        repoName: repo1
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.7-0
  instances:
  - dataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
    name: ""
    replicas: 1
  port: 5432
  postgresVersion: 14