apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGUpgrade
metadata:
  name: cluster-gcs-upgrade
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.3.1-0
  postgresClusterName: cluster-gcs
  fromPostgresVersion: 14
  toPostgresVersion: 15